services:
  postgres:
    image: postgres:17-alpine
    container_name: argus_database
    environment:
      POSTGRES_USER: ${DB_USER:-argus}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_NAME:-argus}
    ports:
      - "5432:5432"
    volumes:
      - argus_postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  argus_postgres_data: